name: dolores

services:
  dolores:
    image:
    container_name: dolores
    restart: unless-stopped

  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4
    container_name: lavalink
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=-Xmx6G
      - SERVER_PORT=2333
      - SERVER_ADDRESS=0.0.0.0
      - SERVER_HTTP2_ENABLED=true
      - LAVALINK_SERVER_PASSWORD=
      - LAVALINK_SERVER_SOURCES_YOUTUBE=true
      - LAVALINK_SERVER_SOURCES_BANDCAMP=false
      - LAVALINK_SERVER_SOURCES_SOUNDCLOUD=false
      - LAVALINK_SERVER_SOURCES_TWITCH=false
      - LAVALINK_SERVER_SOURCES_VIMEO=false
      - LAVALINK_SERVER_SOURCES_HTTP=true
      - LAVALINK_SERVER_SOURCES_LOCAL=false
      - LAVALINK_PLUGINS_DIR=/opt/Lavalink/plugins/
    volumes:
      - C:\{Docker folder}\lavalink\plugins/:/opt/Lavalink/plugins/
    networks:
      - lavalink
    expose:
      # lavalink exposes port 2333 to connect to for other containers (this is for documentation purposes only)
      - 2333
    ports:
      # you only need this if you want to make your lavalink accessible from outside of containers
      - "2333:2333"
networks:
  # create a lavalink network you can add other containers to, to give them access to Lavalink
  lavalink:
    name: lavalink
