[project]
name = "dolores"
version = "0.1.11"
description = "Discord bot named Dolores"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "apprise==1.9.2",
    "openai==1.61.1",
    "pomice==2.9.2",
    "py-cord[voice]==2.6.1",
    "python-dotenv==1.0.1",
    "requests==2.32.3",
    "tenacity>=9.0.0",
]
