# Contains all config options for Dolores
DISCORD:
  bot_api_key: Bot API Key Here
  diffusion_key: Stable Diffusion Key Here
YTDL:
  format: bestaudio/best
  outtmpl: '%(extractor)s-%(id)s-%(title)s.%(ext)s'
  restrictfilenames: True
  noplaylist: True
  nocheckcertificate: True
  ignoreerrors: False
  logtostderr: False
  quiet: True
  no_warnings: True
  default_search: auto
  source_address: '0.0.0.0'
