# Contains all config options for Dolores
DISCORD:
  bot_api_key: BOT_API_KEY
  test_bot_api_key: TEST_BOT_API_KEY
  sarcastic_names:  ['my lovely','darling','sweetie','sweetie-pie','my sugar lump princess','my big strong warrior','dearest','lover','honey','foxy mama','loathsome dung eater','baby girl','Felicia','mamacita','diva','hunty','Queen','Jan']
  reply_method: openai
  news_channel_id: channel id you want Doloresto watch for summarization
YTDL:
  format: bestaudio/best
  outtmpl: '%(extractor)s-%(id)s-%(title)s.%(ext)s'
  restrictfilenames: True
  noplaylist: True
  nocheckcertificate: True
  ignoreerrors: False
  logtostderr: False
  quiet: True
  no_warnings: True
  default_search: auto
  source_address: '0.0.0.0'
NOTION:
  base_url: https://api.notion.com/v1/
  api_key: API_KEY
  notion_version: '2022-06-28'
  database_id: NOTION_DATABASE_ID_WITH_CALENDAR
TWITCH:
  client_id: TWITCH_CLIENT_ID
  client_secret: TWITCH_CLIENT_SECRET
  broadcaster_name: BROADCASTER_NAME
  broadcaster_id: BROADCASTER_ID
STABLEDIFFUSION:
  api_key: API_KEY
OPENAI:
  api_key: API_KEY
  model: gpt-3.5-turbo
  max_tokens: 60
  temperature: 0.9
  top_p: 1
  frequency_penalty: 0
  presence_penalty: 0.6
SELFHOST:
  ip_address: something
SMMRY:
  api_key: API_KEY
  base_url: https://api.smmry.com
