name: Docker Hub Deployment
on:
    push:
        branches:
          - main
jobs:
    push_to_registry:
        runs-on: ubuntu-latest
        steps:
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USER }}
                password: ${{ secrets.DOCKER_PASS }}
            - name: Build and push Docker image
              uses: docker/build-push-action@v2
              with:
                context: .
                push: true
                tags: exaltatus/dolores:latest
            - name: Logout from Docker Hub
              run: docker logout
