name: Docker Hub Deployment
on:
    push:
        branches:
          - main
jobs:
    push_to_registry:
        runs-on: ubuntu-latest
        env:
            REPO: ${{ secrets.DOCKER_REPO }}
        steps:
            - name: Login to Docker Hub
              run: docker login -u ${{ secrets.DOCKER_USER }}
                            -p ${{ secrets.DOCKER_PASS }}
            - name: Build Docker image
              run: docker build -t $REPO:latest -t $REPO:${GITHUB_SHA::8} .
            - name: Publish Docker image
              run: docker push $REPO
